spring.application.name=equestrian

server.port=8000
server.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/equestrian
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.jpa.show-sql=true

jwt-secret="C6UlILsE6GJwNqwCTkkvJj9O653tfiod3vaGrrTOrJFAUD1wEBnnposzcQl"
jwt-expiration-ms=86400000