spring.application.name=equestrian

server.port=8000
server.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/equestrian
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.jpa.show-sql=true

jwt-secret="C6UlILsE6GJwNqwCTkkvJj9O653tfiod3vaGrrTOrJFAUD1wEBnnposzcQl"
jwt-expiration-ms=86400000
jwt-verification-expiration-ms= 3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app-base-url=http://localhost:${server.port}